<!ELEMENT list (skill)*>
        <!ELEMENT skill (table|set|enchant1|enchant2|for|cond|triggers)*>
        <!ATTLIST skill
                id CDATA #REQUIRED
                levels CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT table (#PCDATA)>
        <!ATTLIST table
                name CDATA #REQUIRED>
        <!ELEMENT set (and|using)*>
        <!ATTLIST set
                name CDATA #IMPLIED
                order CDATA #IMPLIED
                stat CDATA #IMPLIED
                val CDATA #REQUIRED>
        <!ELEMENT enchant1 (table)*>
        <!ATTLIST enchant1
                levels CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT enchant2 (table)*>
        <!ATTLIST enchant2
                levels CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT for (effect|add|mul|set|sub)*>
        <!ELEMENT effect (add|def|player|mul|sub|target|set|triggers|game|has)*>
        <!ATTLIST effect
                abnormal CDATA #IMPLIED
                abnormal2 CDATA #IMPLIED
                abnormal3 CDATA #IMPLIED
                applyOnCaster CDATA #IMPLIED
                applyOnSummon CDATA #IMPLIED
                chance CDATA #IMPLIED
                count CDATA #IMPLIED
                displayId CDATA #IMPLIED
                displayLevel CDATA #IMPLIED
                effectPower CDATA #IMPLIED
                effectType CDATA #IMPLIED
                isOffensive CDATA #IMPLIED
                isReflectable CDATA #IMPLIED
                name CDATA #REQUIRED
                stackOrder CDATA #IMPLIED
                stackType CDATA #IMPLIED
                stackType2 CDATA #IMPLIED
                time CDATA #IMPLIED
                cancelOnAction CDATA #IMPLIED
                cancelOnItemSwitch CDATA #IMPLIED
                isSaveable CDATA #IMPLIED
                isCancelable CDATA #IMPLIED
                val CDATA #IMPLIED>
        <!ELEMENT add (using|or|player|and|game|target)*>
        <!ATTLIST add
                order CDATA #REQUIRED
                stat CDATA #REQUIRED
                val CDATA #REQUIRED>
        <!ELEMENT cond (and|player|target|not|or|has|zone|using)*>
        <!ATTLIST cond
                addName CDATA #IMPLIED
                msgId CDATA #IMPLIED
                customMessage CDATA #IMPLIED>
        <!ELEMENT and (using|player|target|not)*>
        <!ELEMENT using (#PCDATA)>
        <!ATTLIST using
                armor CDATA #IMPLIED
                blowskill CDATA #IMPLIED
                kind CDATA #IMPLIED>
        <!ELEMENT player (#PCDATA)>
        <!ATTLIST player
                aggro CDATA #IMPLIED
                pvp CDATA #IMPLIED
                player CDATA #IMPLIED
                exclude_caster CDATA #IMPLIED
                summon CDATA #IMPLIED
                mob CDATA #IMPLIED
                npc CDATA #IMPLIED
                targetInTheSameParty CDATA #IMPLIED
                targetInTheSameClan CDATA #IMPLIED
                targetInTheSameAlly CDATA #IMPLIED
                mobId CDATA #IMPLIED
                race CDATA #IMPLIED
                npc_class CDATA #IMPLIED
                playerRace CDATA #IMPLIED
                forbiddenClassIds CDATA #IMPLIED
                playerSameClan CDATA #IMPLIED
                castledoor CDATA #IMPLIED
                direction CDATA #IMPLIED
                percentHP CDATA #IMPLIED
                percentMP CDATA #IMPLIED
                percentCP CDATA #IMPLIED
                hasBuffId CDATA #IMPLIED
                hasBuff CDATA #IMPLIED
                hasForbiddenSkill CDATA #IMPLIED
                race CDATA #IMPLIED
                forbiddenClassIds CDATA #IMPLIED
                minLevel CDATA #IMPLIED
                summon_siege_golem CDATA #IMPLIED
                maxLevel CDATA #IMPLIED
                maxPK CDATA #IMPLIED
                resting CDATA #IMPLIED
                moving CDATA #IMPLIED
                running CDATA #IMPLIED
                standing CDATA #IMPLIED
                flying CDATA #IMPLIED
                flyingTransform CDATA #IMPLIED
                olympiad CDATA #IMPLIED
                is_in_team CDATA #IMPLIED
                on_pvp_event CDATA #IMPLIED
                is_hero CDATA #IMPLIED
                is_clan_leader CDATA #IMPLIED
                is_in_academy CDATA #IMPLIED
                is_premium CDATA #IMPLIED
                is_in_combat CDATA #IMPLIED
                class_is_mage CDATA #IMPLIED
                min_pledge_rank CDATA #IMPLIED
                percentHP CDATA #IMPLIED
                percentMP CDATA #IMPLIED
                percentCP CDATA #IMPLIED
                chargesMin CDATA #IMPLIED
                chargesMax CDATA #IMPLIED
                agathion CDATA #IMPLIED
                cubic CDATA #IMPLIED
                instance_zone CDATA #IMPLIED
                riding CDATA #IMPLIED
                strider CDATA #IMPLIED
                wyvern CDATA #IMPLIED
                none CDATA #IMPLIED
                classId CDATA #IMPLIED
                privateStoreType CDATA #IMPLIED
                gender CDATA #IMPLIED
                hasBuffId CDATA #IMPLIED
                hasBuff CDATA #IMPLIED
                damage CDATA #IMPLIED
                skillMinSeed CDATA #IMPLIED>
        <!ELEMENT def (#PCDATA)>
        <!ATTLIST def
                name CDATA #REQUIRED
                val CDATA #REQUIRED>
        <!ELEMENT mul (target|using|not|and|player|or)*>
        <!ATTLIST mul
                order CDATA #REQUIRED
                stat CDATA #REQUIRED
                val CDATA #REQUIRED>
        <!ELEMENT target (#PCDATA)>
        <!ATTLIST target
                aggro CDATA #IMPLIED
                pvp CDATA #IMPLIED
                player CDATA #IMPLIED
                exclude_caster CDATA #IMPLIED
                summon CDATA #IMPLIED
                mob CDATA #IMPLIED
                npc CDATA #IMPLIED
                targetInTheSameParty CDATA #IMPLIED
                targetInTheSameClan CDATA #IMPLIED
                targetInTheSameAlly CDATA #IMPLIED
                mobId CDATA #IMPLIED
                race CDATA #IMPLIED
                npc_class CDATA #IMPLIED
                playerRace CDATA #IMPLIED
                forbiddenClassIds CDATA #IMPLIED
                playerSameClan CDATA #IMPLIED
                castledoor CDATA #IMPLIED
                direction CDATA #IMPLIED
                percentHP CDATA #IMPLIED
                percentMP CDATA #IMPLIED
                percentCP CDATA #IMPLIED
                hasBuffId CDATA #IMPLIED
                hasBuff CDATA #IMPLIED
                hasForbiddenSkill CDATA #IMPLIED
                race CDATA #IMPLIED
                forbiddenClassIds CDATA #IMPLIED
                minLevel CDATA #IMPLIED
                summon_siege_golem CDATA #IMPLIED
                maxLevel CDATA #IMPLIED
                maxPK CDATA #IMPLIED
                resting CDATA #IMPLIED
                moving CDATA #IMPLIED
                running CDATA #IMPLIED
                standing CDATA #IMPLIED
                flying CDATA #IMPLIED
                flyingTransform CDATA #IMPLIED
                olympiad CDATA #IMPLIED
                is_in_team CDATA #IMPLIED
                on_pvp_event CDATA #IMPLIED
                is_hero CDATA #IMPLIED
                is_clan_leader CDATA #IMPLIED
                is_in_academy CDATA #IMPLIED
                is_premium CDATA #IMPLIED
                is_in_combat CDATA #IMPLIED
                class_is_mage CDATA #IMPLIED
                min_pledge_rank CDATA #IMPLIED
                percentHP CDATA #IMPLIED
                percentMP CDATA #IMPLIED
                percentCP CDATA #IMPLIED
                chargesMin CDATA #IMPLIED
                chargesMax CDATA #IMPLIED
                agathion CDATA #IMPLIED
                cubic CDATA #IMPLIED
                instance_zone CDATA #IMPLIED
                riding CDATA #IMPLIED
                strider CDATA #IMPLIED
                wyvern CDATA #IMPLIED
                none CDATA #IMPLIED
                classId CDATA #IMPLIED
                privateStoreType CDATA #IMPLIED
                gender CDATA #IMPLIED
                hasBuffId CDATA #IMPLIED
                hasBuff CDATA #IMPLIED
                damage CDATA #IMPLIED
                skillMinSeed CDATA #IMPLIED>
        <!ELEMENT sub (using|and)*>
        <!ATTLIST sub
                order CDATA #REQUIRED
                stat CDATA #REQUIRED
                val CDATA #REQUIRED>
        <!ELEMENT or (player|using|target)*>
        <!ELEMENT not (using|player|target)*>
        <!ELEMENT game (#PCDATA)>
        <!ATTLIST game
                night CDATA #REQUIRED>
        <!ELEMENT has (#PCDATA)>
        <!ATTLIST has
                skill CDATA #IMPLIED
                success CDATA #IMPLIED>
        <!ELEMENT zone (#PCDATA)>
        <!ATTLIST zone
                type CDATA #REQUIRED>
        <!ELEMENT triggers (trigger)*>
        <!ELEMENT trigger (player)*>
        <!ATTLIST trigger
                chance CDATA #REQUIRED
                id CDATA #REQUIRED
                level CDATA #REQUIRED
                type CDATA #REQUIRED>